# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address_city', models.CharField(max_length=30)),
                ('address_district', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('joined_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='employeeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('number_of_employee', models.IntegerField()),
                ('heirarchy', models.IntegerField(choices=[(0, 'ADMIN'), (1, 'SUPER'), (2, 'STAFF')])),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.employee')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employeeCategory'),
        ),
    ]
