# Generated by Django 3.0.7 on 2020-06-26 13:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('billno', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('patientsname', models.CharField(max_length=30)),
                ('discount', models.FloatField()),
                ('staffid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('itemscode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('itemsname', models.CharField(max_length=50)),
                ('categoryname', models.CharField(max_length=40)),
                ('locationname', models.CharField(max_length=20)),
                ('reorderlimit', models.IntegerField()),
                ('maxlimit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('billno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.bill')),
                ('medid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='batchdata',
            fields=[
                ('batchno', models.DateField(primary_key=True, serialize=False)),
                ('expdate', models.CharField(default='2017/09', max_length=8, validators=[django.core.validators.RegexValidator(message='Date doesnt comply', regex='((20)(1([2-9])|([2-9])([0-9])))/((0[1-9])|(1[0-2]))')])),
                ('stock', models.CharField(max_length=10)),
                ('itemscode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='amount',
            fields=[
                ('batchno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.batchdata')),
                ('costprice', models.FloatField()),
                ('sellprice', models.FloatField()),
                ('itemscode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.medicine')),
            ],
        ),
    ]
