# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('itemscode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('itemsname', models.CharField(max_length=50)),
                ('categoryname', models.CharField(max_length=40)),
                ('locationname', models.CharField(max_length=20)),
                ('reorderlimit', models.IntegerField()),
                ('maxlimit', models.IntegerField()),
            ],
        ),
    ]
