# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='batchdata',
            fields=[
                ('batchno', models.IntegerField(primary_key=True, serialize=False)),
                ('expdate', models.DateField()),
                ('stock', models.CharField(max_length=10)),
                ('itemscode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.medicine')),
            ],
        ),
    ]
