# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170715_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchdata',
            old_name='exptag_validator',
            new_name='expdate',
        ),
    ]
