# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170715_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchdata',
            old_name='itemscode',
            new_name='itemscode_id',
        ),
    ]
