# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('billno', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('patientsname', models.CharField(max_length=30)),
                ('discount', models.FloatField()),
                ('staffid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.RenameField(
            model_name='amount',
            old_name='itemscode_id',
            new_name='itemscode',
        ),
        migrations.RemoveField(
            model_name='amount',
            name='batchno_id',
        ),
        migrations.RemoveField(
            model_name='amount',
            name='id',
        ),
        migrations.AddField(
            model_name='amount',
            name='batchno',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.batchdata'),
            preserve_default=False,
        ),
    ]
