# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
